#!/usr/bin/env bash
#
# Builds Analyzer.app.
#
# Deliberately a script rather than an Xcode project. A .pbxproj is a large
# generated file that is painful to review and merge, and everything needed here
# is three commands: build the Rust staticlib, compile Swift against it, and lay
# out a bundle. It also means CI can build the app without Xcode project
# tooling.
#
# Usage: ./build.sh [--release] [--run]

set -euo pipefail

cd "$(dirname "$0")"
ROOT="$(cd ../.. && pwd)"

# Plain strings rather than arrays: macOS still ships bash 3.2, where expanding
# an empty array under `set -u` is an error.
PROFILE="debug"
CARGO_FLAGS=""
SWIFT_FLAGS="-Onone -g"
RUN=0

for arg in "$@"; do
    case "$arg" in
        --release)
            PROFILE="release"
            CARGO_FLAGS="--release"
            SWIFT_FLAGS="-O"
            ;;
        --run) RUN=1 ;;
        *) echo "unknown option: $arg" >&2; exit 2 ;;
    esac
done

export PATH="/opt/homebrew/opt/rustup/bin:$HOME/.cargo/bin:$PATH"

APP="build/Analyzer.app"
LIB="$ROOT/target/$PROFILE/libanalyzer_ffi.a"
HEADER_DIR="$ROOT/crates/analyzer-ffi/include"

echo "==> building the Rust core ($PROFILE)"
# shellcheck disable=SC2086 # deliberate word splitting of the flag string
cargo build --manifest-path "$ROOT/Cargo.toml" -p analyzer-ffi $CARGO_FLAGS

if [[ ! -f "$HEADER_DIR/analyzer.h" ]]; then
    echo "error: $HEADER_DIR/analyzer.h was not generated by cbindgen" >&2
    exit 1
fi

# The module map has to sit beside the header it names.
cp include/module.modulemap "$HEADER_DIR/module.modulemap"

echo "==> compiling Swift"
rm -rf "$APP"
mkdir -p "$APP/Contents/MacOS" "$APP/Contents/Resources"

# shellcheck disable=SC2086
swiftc $SWIFT_FLAGS \
    -parse-as-library \
    -target arm64-apple-macos14.0 \
    -I "$HEADER_DIR" \
    -Xcc -fmodule-map-file="$HEADER_DIR/module.modulemap" \
    -Xcc -std=c23 \
    -framework AppKit -framework SwiftUI -framework Metal -framework MetalKit \
    -framework CoreAudio -framework AudioToolbox -framework CoreFoundation \
    "$LIB" \
    Sources/*.swift \
    -o "$APP/Contents/MacOS/Analyzer"

cp Resources/Info.plist "$APP/Contents/Info.plist"

echo "==> signing"
# Ad-hoc is enough to run locally. Distribution needs a Developer ID and
# notarisation, which is a separate concern with its own credentials.
codesign --force --sign - \
    --entitlements /dev/null \
    --identifier dev.rossbower.analyzer \
    "$APP" 2>/dev/null || codesign --force --sign - "$APP"

echo "==> built $APP"

if [[ "$RUN" == "1" ]]; then
    echo "==> launching"
    open "$APP"
fi
